In [3]:
import numpy as np 
  
class AddBorder:
    
    def add_border_with_zeros(self):
        """
        function to add a border (filled with 0's)
        around an existing array
        """
        original = np.ones((3, 3))  # creating a 3*3 matrix with 1
        print("Original array is :\n", original)   
        original = np.pad(original, pad_width=1, mode='constant', constant_values=0) # add border of 0 around 3*3 matrix of 1
        print("Updated array by add the border filled with 0 is :\n", original) 

if __name__ == "__main__":
    BorderAdd = AddBorder()
    BorderAdd.add_border_with_zeros()

Original array is :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Updated array by add the border filled with 0 is :
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
