In [6]:
import numpy as np 
  
class ArrayShape:
    
    def create_array_shape_and_multiply(self):
        """
        function to create an array of (3, 4) shape, multiply 
        every element value by 3 and display the new array
        """
        my_array = np.arange(12).reshape(3, 4)
        print("Original array is :\n",my_array)
        for a in np.nditer(my_array, op_flags=['readwrite']):
            a[...] = 3 * a
        print("Updated Array is :\n",my_array)
        
if __name__ == "__main__":
    Shape = ArrayShape()
    Shape.create_array_shape_and_multiply()
    

Original array is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Updated Array is :
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
