In [16]:
import numpy as np 
  
class ChangeDataType:
    
    def change_data_type_of_array(self):
        """
        function to change the data type of an array
        """
        my_array = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
        print("Original Array is: \n", my_array)
        print("Before chnaging the data type of the array is :", my_array.dtype)
        new_array = my_array.astype(float) # Change the data type 
        print("After chnaging the data type of the array is :",new_array.dtype, "\nNew Array is: \n", new_array)


        
if __name__ == "__main__":
    DataTypeChange = ChangeDataType()
    DataTypeChange.change_data_type_of_array()

Original Array is: 
 [[ 2  4  6]
 [ 6  8 10]]
Before chnaging the data type of the array is : int32
After chnaging the data type of the array is : float64 
New Array is: 
 [[ 2.  4.  6.]
 [ 6.  8. 10.]]
