In [4]:
import numpy as np 
  
class CheckerBoard:
    
    def checker_board_pattern(self):
        """
        function to create a 8x8 matrix and
        fill it with a checkerboard pattern
        """
        x = np.ones((3,3))
        x = np.zeros((8,8),dtype=int)
        x[1::2,::2] = 1 # Slice from 1st index row till 1+2+2.. and fill all columns with 1 starting from 0th to 0+2+2... and so on.
        x[::2,1::2] = 1 # Slice from 0th row till 0+2+2.. and fill all columns with 1 starting from 1 to 1+2+2+..
        print("Checkerboard pattern is :\n", x)
        

if __name__ == "__main__":
    Pattern = CheckerBoard()
    Pattern.checker_board_pattern()

Checkerboard pattern is :
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
