In [4]:
import numpy as np

class CreateMatrix:
    
    def create_matrix(self):
        """
        function create a 3x3 matrix 
        values ranging from 2 to 10
        """
        matrix =  np.arange(2, 11).reshape(3,3)
        print(matrix)
        
if __name__ == "__main__":
    MatrixCreation = CreateMatrix()
    MatrixCreation.create_matrix()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
