In [17]:
import numpy as np

class CreateBorder:
    
    def create_border_with_one(self):
        """
        function to create a 2d array with
        1 on the border and 0 inside
        """
        original = np.ones((5,5)) # creating a 5*5 matrix with 1
        print("Original array is :\n", original)
        original[1:-1,1:-1] = 0
        print("Updated array with 1 on the border and 0 inside is :\n", original)
        
if __name__ == "__main__":
    BorderCreate = CreateBorder()
    BorderCreate.create_border_with_one()

Original array is :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Updated array with 1 on the border and 0 inside is :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
