In [1]:
import numpy as np 
  
class Diagonal:
    
    def create_ones_on_diagonal(self):
        """
        function to create a 2-D array with 3*3 matrix in
        ones on a diagonal and zeros elsewhere.
        """
        my_array = np.eye(3) # The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere.
        print("2-D array is: \n", my_array)

if __name__ == "__main__":
    CreateDiagonal = Diagonal()
    CreateDiagonal.create_ones_on_diagonal()

3-D array is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
