In [5]:
import numpy as np 
  
class FlattenedArray:
    
    def create_flattened_array(self):
        """
        function to create a contiguous flattened array
        """
        my_array = np.array([[10, 20, 30], [20, 40, 50]])
        print("Original array is :\n", my_array)
        flattened_array = my_array.ravel() #ravel() return only view of original array , can also use flatten()
        print("Flattened array is :\n", flattened_array)
        
if __name__ == "__main__":
    ArrayFlattened = FlattenedArray()
    ArrayFlattened.create_flattened_array()
    

Original array is :
 [[10 20 30]
 [20 40 50]]
Flattened array is :
 [10 20 30 20 40 50]
