In [6]:
import numpy as np 
  
class ConvertToArray:
    
    def list_and_tuple_into_array(self):
        """
        function to convert a list
        and tuple into arrays
        """
        my_list = [1, 2, 3, 4, 5, 6, 7, 8]
        print("List to array is: \n", np.asarray(my_list)) # array (by default) will make a copy of the object, while asarray will not unless necessary
        my_tuple = ([8, 4, 6], [1, 2, 3])
        print("Tuple to array is: \n", np.asarray(my_tuple))
    
if __name__ == "__main__":
    ArrayConversion = ConvertToArray()
    ArrayConversion.list_and_tuple_into_array()

List to array is: 
 [1 2 3 4 5 6 7 8]
Tuple to array is: 
 [[8 4 6]
 [1 2 3]]
