In [5]:
import numpy as np 
  
class Pattern:
    
    def create_pattern(self):
        """
        function to create a 2-D array in given pattern
        """ 
        my_array = np.tri(4, 3, -1) # An array with ones at and below the given diagonal and zeros elsewhere. SYntax is numpy.tri(N(rows), M=None(cols), k=0, dtype=<class 'float'>)
        print("2-D array is: \n", my_array)

if __name__ == "__main__":
    CreatePattern = Pattern()
    CreatePattern.create_pattern()

2-D array is: 
 [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
